name: autobahn tests

on:
  push:
    branches:
      - mistress
  pull_request:

jobs:
  autobahn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.2"
          gleam-version: "1.16.0"
          rebar3-version: "3"

      - name: Downloading dependencies
        run: gleam deps download

      - name: Start WebSocket server
        run: gleam run -m autobahn &

      - name: Wait for WebSocket server to start
        run: sleep 5

      - name: Run autobahn tests (expected to have no panics)
        run: |
          docker run --rm \
            -v "${PWD}/autobahn/config.json:/autobahn.json" \
            -v "${PWD}/autobahn:/reports" \
            --network host \
            crossbario/autobahn-testsuite \
            wstest -m fuzzingclient -s /autobahn.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: autobahn-reports
          path: autobahn/server/
