name: gleam tests

on:
  push:
    branches:
      - mistress
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.2"
          gleam-version: "1.16.0"
          rebar3-version: "3"

      - name: Downloading dependencies
        run: gleam deps download

      - name: Running gleam tests
        run: gleam test

      - name: Check code formatting
        run: gleam format --check src test
